# Generated by Django 5.2.7 on 2025-11-24 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_cashier_65e49a_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'date_created'], name='sales_cashier_fcf9e1_idx'),
        ),
    ]
