# Generated by Django 5.2.7 on 2025-11-09 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_last_utang_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Number of individual units in one pack. Use 1 for single-piece products.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
