# Generated by Django 5.2.7 on 2025-11-24 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shift_sale_shift_shift_shifts_user_id_eddc91_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shift',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
