# Generated by Django 5.2.7 on 2025-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_pack_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='added_to_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='profit_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('bundle', 'Bundle'), ('pack', 'Pack')], default='piece', help_text='Unit used for this purchase (pack or piece)', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: selling price per piece', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, help_text='Number of sellable units inside a pack. Set to 1 for single-piece purchases'),
        ),
    ]
