# Generated by Django 5.2.7 on 2025-11-25 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_shift_closing_cash_shift_opening_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift when payment was received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.shift'),
        ),
    ]
