# Generated by Django 5.2.7 on 2025-11-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_payment_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('SALE_MODIFIED', 'Sale Modified'), ('SALE_VOIDED', 'Sale Voided'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('ROLE_CHANGED', 'Role Changed'), ('INVENTORY_UPDATE', 'Inventory Updated'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('CUSTOMER_DELETED', 'Customer Deleted'), ('PAYMENT_RECORDED', 'Payment Recorded')], max_length=50),
        ),
    ]
